### ISSUE TITLE
ECDF Plot Axes Flipped in "Staircase"

### ISSUE THREAD

**Issue by PiacentinoLab** [justinbois/iqplot#1]
Hey Justin,
Great new package, iqplot is super easy to use and powerful! I just installed and made a few ECDF plots, but ran into an issue. When I plot a standard ECDF it looks great, but when I turn on 'staircase' or 'formal' styles, the x and y axes have flipped positions. Their labels remain in the correct place, but the values have swapped axes. 

I've found a workaround using the q_axis feature to flip axes, then rename manually. For this replication code, I followed your Basic usage notebook to download and plot sample data (https://iqplot.github.io/user_guide/user_guide.html#ECDFs). 

`import iqplot` 
`import bokeh.sampledata.autompg`
`import bokeh.io`
`bokeh.io.output_notebook()`
`df = bokeh.sampledata.autompg.autompg_clean` 

Then I plotted as described... 
`raw_ecdf = iqplot.ecdf(data=df, q="mpg", cats="origin", title="raw ecdf")` 

...and compared to the staircase mode 
`staircase_ecdf = iqplot.ecdf(data=df, q="mpg", cats="origin", title="staircase ecdf", style='staircase')`

Like this, the axes are flipped.

I fixed this using the following code:
`fixed_axes = iqplot.ecdf(data=df, q="mpg", cats="origin", title="fixed axes ecdf", style='staircase', q_axis='y', x_axis_label='mpg', y_axis_label='ECDF')`

Is this a bug, or is there a reason to flip the axes that I'm unaware of?

Thanks!
-Mike

**Comment by justinbois** [comment]
Definitely a bug. I'll squash it very soon. Thanks for reporting!

**Comment by justinbois** [comment]
Fixed, in v. 0.1.4.
