### ISSUE TITLE
Broken link in https://iqplot.github.io/getting_started/purpose.html#why-iqplot

### ISSUE THREAD

**Issue by rlearsch** [justinbois/iqplot#18]
Hi Justin! Hope you're good. I was plotting an ECDF and hit an extremely minor typo in your github page here (https://iqplot.github.io/getting_started/purpose.html#why-iqplot)

```
- **Plots without a categorical axis**

    + `Histograms <https://en.wikipedia.org/wiki/Histogram>`_
    + `ECDFs <https://en.wikipedia.org/wiki/Empirical_distribution_function)>`_
```
The link on **ECDFs** is broken: https://en.wikipedia.org/wiki/Empirical_distribution_function) takes you to a non-page on wikipedia, while removing the trailing ) brings you to the correct page:
[https://en.wikipedia.org/wiki/Empirical_distribution_function](https://en.wikipedia.org/wiki/Empirical_distribution_function)

**Comment by justinbois** [comment]
Fixed in most recent version.
