### ISSUE TITLE
Update import of `dummy_jit`

### ISSUE THREAD

**Issue by jasper-tms** [justinbois/iqplot#24]
Hi Justin,

After this summer's bootcamp I found myself wanting to make some ecdfs. I just installed iqplot using pip and tried to get to it, but `import iqplot` was raising an error that seems to arise from a small and easily fixable issue. It looks like numba was previously in `requirements.txt` but isn't anymore, causing `dist.py` to try to run https://github.com/justinbois/iqplot/blob/11933648bf183ad1ecd5d0299e8739b399f237c9/iqplot/dist.py#L15
(where in earlier versions of iqplot this line would essentially never get run since numba would be installed). It looks like two small changes are needed, if I'm seeing things correctly:
- [ ] this function is now starts with an underscore (`utils._dummy_jit` instead of `utils.dummy_jit`) and
- [ ] the `from . import utils` line needs to come before this line

Moving these lines https://github.com/justinbois/iqplot/blob/11933648bf183ad1ecd5d0299e8739b399f237c9/iqplot/dist.py#L10-L15
below `from . import utils` and adding the underscore to the function name worked for me. Alternatively, installing numba also resolves the issue and leads to `import iqplot` succeeding.

Thanks a lot!

**Comment by justinbois** [comment]
Indeed, that is exactly the fix! Thanks, @jasper-tms! It's currently pushed, and I'll cut a bugfix release soon.
