### ISSUE TITLE
stripbox not overlaying box when jitter=True

### ISSUE THREAD

**Issue by tomdmt** [justinbois/iqplot#5]
The stripbox plot plots the data as expected when jitter = True but it no longer overlays the box plot.

**Comment by justinbois** [comment]
Can you please send a minimal example reproducing the bug?

**Comment by tomdmt** [comment]
Actually, I think my problem is that my data is so dense that the box plot is covered by dots. Looking at my graphs when Jitter=False puts the box and whiskers behind the datapoints. It wold be great if the box was on top of points.

**Comment by justinbois** [comment]
Not an issue.
